version: "3.2"
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/postgres-data:/var/lib/postgresql/data
      - ${PWD}/scripts/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=Postgres2024**
      - POSTGRES_USER=postgres
      - POSTGRES_DB=vinyls
      
  vinilos:
    build:
      context: .
    container_name: vinilos-back
    environment:
      DB_HOST: postgres
    ports:
      - '3000:3000'
      - '80:3000'
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src